<h2 style="color:purple;"><b>Numpy Operations</b></h2>

In [1]:
import numpy as np

In [12]:
arr1 = np.arange(21,56,3)
arr2 = np.arange(2,14)

In [13]:
print(arr1)

[21 24 27 30 33 36 39 42 45 48 51 54]


In [15]:
print(arr2)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


<h2 style="color:purple;"><b>Arithmetic operations on arrays </b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Addition</b>
</div>


In [16]:
print(arr1 + arr2)

[23 27 31 35 39 43 47 51 55 59 63 67]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Subtraction</b>
</div>


In [17]:
print(arr1 - arr2)

[19 21 23 25 27 29 31 33 35 37 39 41]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Multiplication</b>
</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>Vector Multiplication: </p>
<p>Multipling an vector with another vector </p>


</div>


In [19]:
print(arr1 * arr2)

[ 42  72 108 150 198 252 312 378 450 528 612 702]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>Scalar Multiplication: </p>
<p>Multipling an vector with a scalar </p>


</div>


In [20]:
print(arr1 * 5)

[105 120 135 150 165 180 195 210 225 240 255 270]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>When we apply any relational opertaion on the elements of the array => It returns boolean array</p>


</div>


In [21]:
print(arr1>2)

[ True  True  True  True  True  True  True  True  True  True  True  True]


In [24]:
arr1

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54])

In [41]:
arr3 = np.arange(1,13).reshape(3,4)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h2 style="color:purple;"><b>Method – 1 : max()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Example 1</b>
</div>


In [23]:
print(arr1.max())

54


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Example 2</b>
</div>



In [42]:
print(arr3.max())

12


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> For 2D-arrays, we can find the max-value 
<ul>
<li>column_wise => axis = 0</li>
<li>Row_wise => axis = 1</li>
</ul></b>
</div>


In [38]:
print(arr3.max(axis = 0))

[ 9 10 11 12]


In [39]:
print(arr3.max(axis = 1))

[ 4  8 12]


<h2 style="color:purple;"><b>Method – 2 : min()</b></h2>


In [25]:
print(arr1.min())

21


In [43]:
print(arr3.min())

1


In [44]:
print(arr3.min(axis = 0))

[1 2 3 4]


In [45]:
print(arr3.min(axis = 1))

[1 5 9]


<h2 style="color:purple;"><b>Method – 3 : std()</b></h2>


In [34]:
print(arr1.std())

10.35615758860399


In [46]:
print(arr3.std())

3.452052529534663


<h2 style="color:purple;"><b>Method – 4 : mean()</b></h2>


In [35]:
print(arr1.mean())

37.5


In [47]:
print(arr1.mean(axis = 0))

37.5


<h2 style="color:purple;"><b>Method – 5 : np.median()</b></h2>


In [36]:
print(np.median(arr1))

37.5


In [48]:
print(np.median(arr1))

37.5


<h2 style="color:purple;"><b>Method – 6 : np.sin()</b></h2>


In [37]:
print(np.sin(arr3))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]
 [ 0.41211849 -0.54402111 -0.99999021 -0.53657292]]


<h2 style="color:purple;"><b>Method – 7 : dot()</b></h2>


In [49]:
arr1

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54])

In [50]:
arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>This is how numpy provides access to linear algebra capabilities  </p>


</div>


In [51]:
print(arr1.dot(arr2))

3804


<h2 style="color:purple;"><b>Method – 8 : np.exp()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>Exponential Function : </p>
<p>exp(arr1[0]) => exp^arr1[0]</p>


</div>


In [56]:
print(np.exp(arr1))

[1.31881573e+09 2.64891221e+10 5.32048241e+11 1.06864746e+13
 2.14643580e+14 4.31123155e+15 8.65934004e+16 1.73927494e+18
 3.49342711e+19 7.01673591e+20 1.40934908e+22 2.83075330e+23]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>This is the reason why numpy is an mathematical library, which uses nd-array data structure, enhances the fastness of python  </p>


</div>
