<h2 style="color:purple;"><b>Ways of Creating ND-Arrays</b></h2>

<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>Numpy is an external library of Python.</p>

  <p>So in order to use this library:</p>

  <ul>
    <li>We need to install it</li>
    <li>After installing, we need to import it inside our code</li>
  </ul>

  <p>⇒ This is similar to using <code>#include</code> in C</p>

</div>


In [2]:
import numpy as np

<h2 style="color:purple;"><b>Method – 1 : np.array()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>We basically pass a list as an input parameter to this np.array() method</p>

<p>np.array() converts the list into the array</p>

<p>1D-arrays are also called as vectors</p></b>

</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Creating 1D-array</b>
</div>


In [3]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Creating 2D-array</b>
</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b><p> When we pass two 1D-array's as an parameter to the np.array() => it creates 2D-array </p>
<p>2D-arrays are similar to matrices</p></b>
</div>


In [5]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Creating 3D-array</b>
</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> When we pass two 2D-array's as an parameter to the np.array() => it creates 3D-array </b>
</div>


In [7]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


<h2 style="color:purple;"><b>Method – 2 : np.zeros()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>We need to pass the shape i.e(no.of rows, no.of cols) as an parameter in the form of tuple to np.zeros()</p>

  <p>It returns the array of given shape where all the elements are <code>zeros</code></p>

  <p>Every element created is of <code>float dtype</code></p>

</div>


In [9]:
arr4 = np.zeros((3,2))
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


<h2 style="color:purple;"><b>Method – 3 : np.ones()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>This is similar to np.zeros(), but every element is <code>one</code> in this array</p>

</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>We have created an 3D-array using np.ones()</p>

</div>


In [10]:
arr5 = np.ones((2,3,4))
print(arr5)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


<h2 style="color:purple;"><b>Method – 4 : np.identity()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>We need to pass an integer as an parameter np.identity()</p>
  <ul>
  <li>  It returns the array, where no.of rows and coumns are equal to the parameter value</li>

  <li>  Diagonal elements are <code>ones's</code>, all other elements are <code>zero's</code></li>
</ul>
</div>


In [11]:
arr6 = np.identity(5)
print(arr6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<h2 style="color:purple;"><b>Method – 5 : np.arange()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>np.arange() creates an array, in a given range</p>
  <p>It contains three parameters:</p>
  <ul>
  <li>lower_bound</li>
  <li>upper_bound</li>
  <li>no.of steps</li>
  </ul>

  <p>upper_bound is mandatory to be specified => but its not included in the array generated, other two parameters are optional</p>

</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>Example – 1:</b>
</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>If no lower_bound is specified, it starts from zero</b>
</div>


In [12]:
arr7 = np.arange(10)
print(arr7)

[0 1 2 3 4 5 6 7 8 9]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>Example – 2:</b>
</div>


In [13]:
arr8 = np.arange(23,34)
print(arr8)

[23 24 25 26 27 28 29 30 31 32 33]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>Example – 3:</b>
</div>


In [14]:
arr9 = np.arange(78,100,3)
print(arr9)

[78 81 84 87 90 93 96 99]


<h2 style="color:purple;"><b>Method – 6 : np.linspace()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>np.linspace() creates an array of given range, with specified no. of points, where each point is equi-distant from its adjacent point</p>
  <p>It contains three parameters:</p>
  <ul>
  <li>lower_bound</li>
  <li>upper_bound</li>
  <li>no.of equi-distant points</li>
  </ul>

  <p>All parameters are mandatory to be specified</p>
  <p>Every element created is of <code>float dtype</code></p>

</div>


In [15]:
arr10 = np.linspace(1,10,10)
print(arr10)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


<h2 style="color:purple;"><b>Method – 7 : np.copy()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>np.copy() creates copy of the original array</p>

</div>


In [16]:
arr11 = arr10.copy()
print(arr11)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
