<h2 style="color:purple;"><b>Indexing, Slicing and Iteration</b></h2>

<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
<ul>
  
  <li>Indexing : Accessing single element from an array </li>
  <p></p>
  <li>Slicing : Accessing more than one element from an array</li>
 <p></p>
  <li>Iteration : Sequentially traversing all the elements of an array</li>
 </ul> 

</div>


In [1]:
import numpy as np

<h2 style="color:purple;"><b>For 1D Arrays</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Example 1</b>
</div>


In [2]:
arr1 = np.array([23,10,45,88,94,58])
print(arr1)

[23 10 45 88 94 58]


In [3]:
print(arr1[3])

88


In [4]:
print(arr1[:5])

[23 10 45 88 94]


In [5]:
print(arr1[-1])

58


<h2 style="color:purple;"><b>For 2D Arrays</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Example 2</b>
</div>


In [11]:
arr2 = np.arange(12,36,2).reshape(4,3)

In [12]:
print(arr2)

[[12 14 16]
 [18 20 22]
 [24 26 28]
 [30 32 34]]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> When we apply indexing of 1D arrays, on 2D-array, it returns entire row </b>
</div>


In [13]:
print(arr2[2])

[24 26 28]


In [14]:
print(arr2[3][2])

34


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Printing the sub-array of a 2D-array </b>
<ul>
    <li><b>We need to specify the rows, and columns need to be displayed in the output screen </b></li>
  </ul>
</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>We are printing the subarray <code>[26 28 30 34]</code> from arr2</p></b></div>


In [16]:
print(arr2[2:,1:])

[[26 28]
 [32 34]]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>We are printing the first column <code>[12 18 24 30]</code> from arr2</p></b></div


In [17]:
print(arr2[:,0])

[12 18 24 30]


In [ ]:
arr1

array([23, 10, 45, 88, 94, 58])

In [22]:
for items in arr1:
    print(items)

23
10
45
88
94
58


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>If we iterate the 2D-array using a single variable, it displays the array row-wise</p>

</div>


In [20]:
for items in arr2:
    print(items)

[12 14 16]
[18 20 22]
[24 26 28]
[30 32 34]


<h2 style="color:purple;"><b>np.nditer()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> 
<p>np.nditer() : Inorder to print items of an array element-wise</p>

</div>


In [23]:
for items in np.nditer(arr2):
    print(items)

12
14
16
18
20
22
24
26
28
30
32
34
