<h2 style="color:purple;"><b>Properties and Attributes of ND-Arrays</b></h2>

<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>Numpy is a class, so it contains multiple attributes and properties</p>
  <p>We need to create an object for numpy class, to access those attributes and properties

</div>


In [1]:
import numpy as np

<h2 style="color:purple;"><b>Attribute – 1 : np.shape</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px; font-weight:bold;">
  
  <p>np.shape : It returns the shape i.e(no.of rows, no.of columns and how many items of such shape)</p>

</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Example 1</b>
</div>


In [2]:
arr1 = np.array([91,25,33])
print(arr1)

[91 25 33]


In [3]:
arr1.shape

(3,)

<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Example 2</b>
</div>


In [4]:
arr2 = np.array([[56],[89],[10],[21]])
print(arr1)

[91 25 33]


In [6]:
arr2.shape

(4, 1)

<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> Example 3</b>
</div>


In [18]:
arr3 = np.array([[[67,23,90],[89,32,88],[67,10,52]],[[11,54,91],[28,6,44],[22,9,38]]])
print(arr3)

[[[67 23 90]
  [89 32 88]
  [67 10 52]]

 [[11 54 91]
  [28  6 44]
  [22  9 38]]]


In [19]:
print(arr3.shape)

(2, 3, 3)


<h2 style="color:purple;"><b>Attribute – 2 : np.ndim</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b><p> np.dim : It returns the dimensions of the given array </p>
</div>


In [7]:
print(arr1.ndim)

1


In [8]:
print(arr2.ndim)

2


In [20]:
print(arr3.ndim)

3


<h2 style="color:purple;"><b>Attribute – 3 : np.size</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b><p> np.size : It returns the total number of items present within the given array </p>
</div>


In [21]:
print(arr1.size)

3


In [22]:
print(arr2.size)

4


In [23]:
print(arr3.size)

18


<h2 style="color:purple;"><b>Attribute – 4 : np.itemsize</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b><p> np.size : It returns the memory occupied by each element of the array, based on its dtype </p>
</div>


In [24]:
print(arr1.itemsize)

8


In [25]:
print(arr2.itemsize)

8


In [26]:
print(arr3.itemsize)

8


<h2 style="color:purple;"><b>Attribute – 5 : np.dtype</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b><p> np.dtype : It returns the dtype of the array elements </p>
</div>


In [30]:
print(arr1.dtype)

int64


In [31]:
print(arr2.dtype)

int64


In [32]:
print(arr3.dtype)

int64


<h2 style="color:purple;"><b>Property – 1 : np.astype()</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b><p> np.astype() : It an inbuilt method of numpy class, which is used to convert the data_type of array elements </p>
</div>


In [33]:
arr4 = arr3.astype('float')
print(arr4)

[[[67. 23. 90.]
  [89. 32. 88.]
  [67. 10. 52.]]

 [[11. 54. 91.]
  [28.  6. 44.]
  [22.  9. 38.]]]


In [34]:
print(type(arr4))

<class 'numpy.ndarray'>
