## Properties and Attributes of Numpy

In [ ]:
import numpy as np

<h2 style="color:purple;"><b>Attribute – 1 : shape</b></h2>

<div style="background-color:#f3e8ff; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>It returns the no. of rows, columns and how many items of that shape.</b>
</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>Example – 1:</b>
</div>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>Understanding the shape of a NumPy array using a simple 2D array.</b>
</div>


In [ ]:
_array_ = np.array([[19,23,45],[20,84,51]])

In [ ]:
print(_array_)

<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>This shape returns only row and column values => because we have only one 2D-array.</b>
</div>


In [43]:
print(_array_.shape)

(2, 3)


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>Example – 2:</b>
</div>


In [39]:
arr_b = np.array([
                [[19,23],[20,84],[89,56]], 
                [[21,45],[51, 30],[67,15]]
                 ])

In [40]:
print(arr_b)

[[[19 23]
  [20 84]
  [89 56]]

 [[21 45]
  [51 30]
  [67 15]]]


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>This shape returned all the three values i.e no.of items of such shape, rows and columns=> because we have only one 2D-array.</b>
</div>


In [41]:
print(arr_b.shape)

(2, 3, 2)


<h2 style="color:purple;"><b>Attribute – 2 : ndim</b></h2>


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b> It returns the dimension of our array</b>
</div>


In [5]:
print(_array_.ndim)

2


In [ ]:
print(arr_b.ndim)

NameError: name 'arr_b' is not defined

<h2 style="color:purple;"><b>Attribute – 3 : size</b></h2>

<div style="background-color:#f3e8ff; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>It returns total no.of elements in the array</b>
</div>


In [6]:
print(_array_.size)

6


<h2 style="color:purple;"><b>Attribute – 4 : itemsize</b></h2>

<div style="background-color:#f3e8ff; color:black; padding:12px; bor
der-left:4px solid purple; border-radius:8px;">
<b>It returns size_of_the_items based on its data_type</b>
</div>



In [ ]:
print(_array_.itemsize)

8


<h2 style="color:purple;"><b>Attribute – 5 : dtype</b></h2>

<div style="background-color:#f3e8ff; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>It returns the data_type of elements in the array</b>
</div>



In [8]:
print(_array_.dtype)

int64


<h2 style="color:purple;"><b>Property – 1 : dtype</b></h2>

<div style="background-color:#f3e8ff; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>It is used for casting the data_type</b>
</div>



In [10]:
print(_array_.astype('float'))

[[19. 23. 45.]
 [20. 84. 51.]]


In [34]:
print(_array_.dtype)

int64


<div style="background-color:#ede9fe; color:black; padding:12px; border-left:4px solid purple; border-radius:8px;">
<b>Example – 3:</b>
</div>


In [14]:
arr = np.identity(4)

In [15]:
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
arr.shape

(4, 4)

In [17]:
arr.ndim

2

In [18]:
arr.size

16

In [20]:
arr.itemsize

8

In [30]:
arr.dtype

dtype('int64')

In [32]:
arr = arr.astype('int')

In [33]:
print(arr.dtype)

int64
