# Ways of Creating ND-Arrays

#### Initially, we need to install the numpy library, once we have that - we need to import it within our code, inorder to use it in our code

In [51]:
import numpy as np

# Method - 1

## np.array()
#### We need to pass the python list as an parameter to the array()
#### This method converts the list into array

In [52]:
#This is the example of 1D-array creation
arr1 = np.array([1,2,3])


In [53]:
print(arr1)

[1 2 3]


In [54]:
arr1.ndim
#ndim -> helps us to check the dimensions of the array

1

In [55]:
#This is the example of 2D-array creation
arr2=np.array([[12,24,25],[19,45,24]])

In [56]:
print(arr2)

[[12 24 25]
 [19 45 24]]


In [57]:
arr2.ndim
#ndim -> helps us to check the dimensions of the array

2

In [ ]:
#This is the example of 3D-array creation
arr3=np.array([
    [[1,41],[97,15]],
    [[67,89],[48,70]]
    ])

In [59]:
print(arr3)

[[[ 1 41]
  [97 15]]

 [[67 89]
  [48 70]]]


In [60]:
arr3.ndim
#ndim -> helps us to check the dimensions of the array

3

#### All the above 1D, 2D and 3D arrays are created using the np.array() method

In [61]:
print(type(arr1))

<class 'numpy.ndarray'>


In [62]:
print(type(arr2))

<class 'numpy.ndarray'>


In [63]:
print(type(arr3))

<class 'numpy.ndarray'>


# Method - 2

## np.zeros()
#### We need to pass the shape of the array (i.e no.of rows and columns) in the form of tuple to the zeros()
#### This method generates the array of given shape 
##### - in which all elements are zero 
##### - all elements are of float dtype

In [64]:
arr4=np.zeros((3,2))

In [65]:
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Method - 3

## np.ones()
#### We need to pass the shape of the array (i.e no.of rows and columns) in the form of tuple to the np.ones()
#### This method generates the array of given shape 
##### - This is similar to zero, but here all the elements are ones 
##### - all elements are of float dtype

In [66]:
arr5=np.ones((2,2))

In [67]:
arr5

array([[1., 1.],
       [1., 1.]])

# Method - 4

## np.identity()
#### We need to pass the integer value to the np.ones() 
##### -  This method generates the given integer sized identity matrix
##### - all elements are of float dtype

In [68]:
arr6=np.identity(4)

In [69]:
print(arr6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Method - 5

## np.arange()
#### We can pass atmost 3 parameters:
###### - lower_bound
###### - upper_bound (This is not included in our array)
###### - step_value
#### This method generates the array, that contains the integers of given range 


In [70]:
arr7=np.arange(10)
#Here we considered only upper_bound - This will not be included in our output array

In [71]:
print(arr7)

[0 1 2 3 4 5 6 7 8 9]


In [72]:
print(type(arr7))

<class 'numpy.ndarray'>


In [ ]:
arr8=np.arange(22,29)
print(arr8)
#Here we considered both the lower_bound and upper_bound - upper_bound is not included in our output array

[22 23 24 25 26 27 28]


In [ ]:
arr9=np.arange(45,89,3)
print(arr9)
#Here we considered all the three parameters lower_bound and upper_bound and step_count - upper_bound is not included in our output array

[45 48 51 54 57 60 63 66 69 72 75 78 81 84 87]


# Method - 6

## np.linspace()
#### We need to pass 3 parameters:
###### - lower_bound
###### - upper_bound (This is not included in our array)
###### - no.of equi_distant points
##### - This method generates the array, that contains the elements within the given range 
##### - all elements are of float dtype
##### - when we calculate the difference between any two consecutive points of the array - their distances are equal/same

In [75]:
arr10=np.linspace(0,6,3)

In [76]:
print(arr10)

[0. 3. 6.]


# Method - 7

## np.copy()
#### We need to pass array_name as the parameters
##### - This method generates the copy of the original_array

In [77]:
arr11 = np.arange(2,10,2)
print(arr11)

[2 4 6 8]


In [78]:
arr12 =  np.copy(arr11)
print(arr12)

[2 4 6 8]
